import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AlertCircle,Archive,CalendarDays,CheckCircle2,Clock3,DoorOpen,Download,Home,RefreshCw,Search,X,Eye } from "lucide-react";
import { RoleDashboardShell } from "@/components/dashboard/RoleDashboardShell";
import { apiGetAllAccommodation,apiUpdateAccommodationStatus,apiGetAccommodationSummary } from "@/lib/api";
import "./operations.css";
const navItems=[{id:"overview",label:"Overview",href:"#overview",description:"Occupancy posture, arrivals, and room-allocation workload."},{id:"booking-queue",label:"Booking queue",href:"#booking-queue",description:"Assign rooms, confirm stays, and close completed records."},{id:"arrivals",label:"Arrival board",href:"#arrivals",description:"Focus on upcoming check-ins and room readiness."}];
export const Route=createFileRoute("/dashboard/accommodation")({head:()=>({meta:[{title:"Accommodation Dashboard — PRANASAKHA"}]}),component:AccommodationDashboard});
function AccommodationDashboard(){
 const [requests,setRequests]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[drafts,setDrafts]=useState({}),[savingId,setSavingId]=useState(null),[selected,setSelected]=useState(null);
 async function refresh(){setError("");try{const [r,s]=await Promise.all([apiGetAllAccommodation(),apiGetAccommodationSummary()]);setRequests(r||[]);setSummary(s||null)}catch(e){setError(e.message||"Could not load accommodation requests.")}finally{setLoading(false);setRefreshing(false)}}useEffect(()=>{refresh()},[]);
 function draftFor(i){return drafts[i.id]||{block:i.block||"",room:i.room||""}};
 async function update(item,next){const d=draftFor(item);if(next==="confirmed"&&(!d.block.trim()||!d.room.trim())){setError("Enter a block and room before confirming.");return}setSavingId(item.id);try{await apiUpdateAccommodationStatus(item.id,next,d.block,d.room);setSelected(null);await refresh()}catch(e){setError(e.message||"Could not update booking.")}finally{setSavingId(null)}}
 const filtered=useMemo(()=>requests.filter(i=>{const hay=`${i.full_name||""} ${i.email||""} ${i.block||""} ${i.room||""}`.toLowerCase();return hay.includes(query.trim().toLowerCase())&&(status==="all"||i.status===status)}),[requests,query,status]);
 const pending=requests.filter(x=>x.status==="pending").length,confirmed=requests.filter(x=>x.status==="confirmed").length,closed=requests.filter(x=>x.status==="closed").length,assigned=requests.filter(x=>x.block&&x.room).length;
 const byBlock=useMemo(()=>{const m={};requests.forEach(r=>{const b=r.block||"Unassigned";m[b]=(m[b]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])},[requests]);
 function exportCsv(){const rows=[["Doctor","Email","Block","Room","Check in","Check out","Status"],...filtered.map(r=>[r.full_name||"",r.email||"",r.block||"",r.room||"",r.check_in||"",r.check_out||"",r.status||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="accommodation-requests.csv";a.click();URL.revokeObjectURL(a.href)}
 return <RoleDashboardShell role="Ashram Accommodation Office" title="Accommodation operations" description="Coordinate stays with clearer allocation, arrival, and closure workflows." navItems={navItems} searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search doctor, block or room…">
 {error?<div className="ops-alert ops-alert--error"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss"><X size={15}/></button></div>:null}
 <section id="overview" className="dashboard-view ops-overview"><div className="ops-hero"><div><span className="ops-kicker">Accommodation workspace</span><h2>Stay coordination center</h2><p>See room assignment pressure, upcoming arrivals, and completed stays at a glance.</p></div><button className="ops-button ops-button--tonal" onClick={()=>{setRefreshing(true);refresh()}} disabled={refreshing}><RefreshCw size={16} className={refreshing?"ops-spin":""}/> Refresh</button></div><div className="ops-stat-grid"><div className="ops-stat-card"><span className="ops-stat-icon"><Clock3 size={18}/></span><span>Pending</span><strong>{pending}</strong><small>Waiting for allocation</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><CheckCircle2 size={18}/></span><span>Confirmed</span><strong>{confirmed}</strong><small>Room assigned</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><DoorOpen size={18}/></span><span>Assigned</span><strong>{assigned}</strong><small>Requests with a room</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><Archive size={18}/></span><span>Closed</span><strong>{closed}</strong><small>Completed records</small></div></div><div className="ops-feature-grid"><div className="ops-feature-card"><span className="ops-kicker">Room map</span><h4>Requests by block</h4><div className="ops-feature-list">{byBlock.slice(0,5).map(([b,n])=><div key={b}><span>{b}</span><strong>{n}</strong></div>)}</div></div><div className="ops-feature-card"><span className="ops-kicker">Efficiency</span><h4>Allocation rate</h4><p>Share of requests that already have a block and room.</p><div className="ops-progress"><span style={{width:`${requests.length?Math.round(assigned/requests.length*100):0}%`}}/></div><p>{requests.length?Math.round(assigned/requests.length*100):0}% allocated</p></div><div className="ops-feature-card"><span className="ops-kicker">Actions</span><h4>Operator shortcuts</h4><div className="ops-chip-row"><button className="ops-button ops-button--tonal ops-button--small" onClick={()=>{setStatus("pending");location.hash="#booking-queue"}}>Pending only</button><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> Export CSV</button></div></div></div></section>
 <section id="booking-queue" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Booking queue</span><h3>Accommodation requests</h3><p>Assign block + room inline, inspect records, confirm, or close.</p></div><span className="ops-inline-count">{filtered.length}</span></div><div className="ops-toolbar"><label className="ops-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search doctor, email, block…"/></label><select className="ops-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="closed">Closed</option></select><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> CSV</button></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Doctor</th><th>Block</th><th>Room</th><th>Dates</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="ops-table-empty">Loading requests…</td></tr>:filtered.length===0?<tr><td colSpan={6} className="ops-table-empty"><Home size={18}/> No matching requests.</td></tr>:filtered.map(item=>{const d=draftFor(item);return <tr key={item.id}><td><strong>{item.full_name||item.email}</strong><span>{item.email||"—"}</span></td><td><input value={d.block} disabled={item.status==="closed"} onChange={e=>setDrafts(p=>({...p,[item.id]:{...d,block:e.target.value}}))} placeholder="Block A"/></td><td><input value={d.room} disabled={item.status==="closed"} onChange={e=>setDrafts(p=>({...p,[item.id]:{...d,room:e.target.value}}))} placeholder="412"/></td><td><span>{item.check_in||"—"} → {item.check_out||"—"}</span></td><td><span className={`ops-status-badge ${item.status==="confirmed"?"is-success":item.status==="closed"?"is-info":"is-warning"}`}>{item.status||"pending"}</span></td><td><div className="ops-chip-row"><button className="ops-export-button" onClick={()=>setSelected(item)}><Eye size={14}/> View</button><button className="ops-button ops-button--primary ops-button--small" disabled={savingId===item.id||item.status==="confirmed"||item.status==="closed"} onClick={()=>update(item,"confirmed")}>{item.status==="confirmed"?"Confirmed":savingId===item.id?"Saving…":"Confirm"}</button>{item.status!=="closed"?<button className="ops-button ops-button--tonal ops-button--small" disabled={savingId===item.id} onClick={()=>update(item,"closed")}>Close</button>:null}</div></td></tr>})}</tbody></table></div></section>
 <section id="arrivals" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Arrival board</span><h3>Upcoming check-ins</h3><p>Use dates to prioritize rooms before arrivals.</p></div></div><div className="ops-feature-list">{requests.filter(r=>r.check_in).sort((a,b)=>String(a.check_in).localeCompare(String(b.check_in))).slice(0,12).map(r=><div key={r.id}><span>{r.check_in} · {r.full_name||r.email}</span><strong>{r.block&&r.room?`${r.block} · ${r.room}`:"Unassigned"}</strong></div>)}{!requests.some(r=>r.check_in)?<div><span>No check-in dates available</span><strong>—</strong></div>:null}</div></section>
 {selected?<div className="ops-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="ops-modal" role="dialog" aria-modal="true"><div className="ops-modal-header"><div><h3>Stay details</h3><p>Review the accommodation record before changing it.</p></div><button className="ops-modal-close" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="ops-detail-grid" style={{marginTop:14}}><div className="ops-detail-item"><span>Doctor</span><strong>{selected.full_name||selected.email}</strong></div><div className="ops-detail-item"><span>Email</span><strong>{selected.email||"—"}</strong></div><div className="ops-detail-item"><span>Block</span><strong>{selected.block||"Unassigned"}</strong></div><div className="ops-detail-item"><span>Room</span><strong>{selected.room||"Unassigned"}</strong></div><div className="ops-detail-item"><span>Check in</span><strong>{selected.check_in||"—"}</strong></div><div className="ops-detail-item"><span>Check out</span><strong>{selected.check_out||"—"}</strong></div></div><div className="ops-modal-footer"><button className="ops-button ops-button--tonal" onClick={()=>setSelected(null)}>Close</button></div></div></div>:null}
 </RoleDashboardShell>
}
