import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Activity,AlertCircle,CheckCircle2,Download,RefreshCw,Search,Shield,Users,UserCheck,UserX,ClipboardList,X,ServerCog,Clock3 } from "lucide-react";
import { RoleDashboardShell } from "@/components/dashboard/RoleDashboardShell";
import { apiGetHealth,apiGetITAccounts,apiUpdateITAccountStatus,apiGetITAudit,apiGetITSummary } from "@/lib/api";
import "./operations.css";
const navItems=[{id:"overview",label:"Overview",href:"#overview",description:"Platform health, access posture, and operational signals."},{id:"system-health",label:"System health",href:"#system-health",description:"Live service and database checks."},{id:"account-management",label:"Account management",href:"#account-management",description:"Search and manage staff access."},{id:"audit-log",label:"Audit log",href:"#audit-log",description:"Review recent system activity."}];
export const Route=createFileRoute("/dashboard/it")({head:()=>({meta:[{title:"IT Team Dashboard — PRANASAKHA"}]}),component:ItDashboard});
function ItDashboard(){
 const [health,setHealth]=useState(null),[accounts,setAccounts]=useState([]),[audit,setAudit]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[role,setRole]=useState("all"),[savingId,setSavingId]=useState(null);
 async function refresh(){setError("");try{const [h,a,l,s]=await Promise.all([apiGetHealth(),apiGetITAccounts(),apiGetITAudit(),apiGetITSummary()]);setHealth(h);setAccounts(a||[]);setAudit(l||[]);setSummary(s||null)}catch(e){setError(e.message||"Could not load IT operations.")}finally{setLoading(false)}}useEffect(()=>{refresh()},[]);
 async function toggle(a){setSavingId(a.id);try{const next=await apiUpdateITAccountStatus(a.id,!a.active);setAccounts(r=>r.map(x=>x.id===a.id?next:x));}catch(e){setError(e.message||"Could not update the account.")}finally{setSavingId(null)}}
 const roles=useMemo(()=>[...new Set(accounts.map(a=>a.role).filter(Boolean))].sort(),[accounts]);
 const filtered=useMemo(()=>accounts.filter(a=>`${a.full_name||""} ${a.email||""} ${a.role||""} ${a.department||""}`.toLowerCase().includes(query.trim().toLowerCase())&&(role==="all"||a.role===role)),[accounts,query,role]);
 const active=accounts.filter(x=>x.active).length,suspended=accounts.length-active;
 function exportCsv(){const rows=[["Name","Email","Role","Department","Status"],...filtered.map(a=>[a.full_name||"",a.email||"",a.role||"",a.department||"",a.active?"Active":"Suspended"])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="pranasakha-accounts.csv";a.click();URL.revokeObjectURL(a.href)}
 return <RoleDashboardShell role="IT Team" title="IT operations" description="Monitor service health, access, and audit signals from one compact workspace." navItems={navItems} searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search name, role or email…">
 {error?<div className="ops-alert ops-alert--error"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss"><X size={15}/></button></div>:null}
 <section id="overview" className="dashboard-view ops-overview"><div className="ops-hero"><div><span className="ops-kicker">IT workspace</span><h2>Platform operations center</h2><p>Keep service reachability, access posture, and recent changes visible without excess density.</p></div><button className="ops-button ops-button--tonal" onClick={refresh}><RefreshCw size={16}/> Refresh</button></div><div className="ops-stat-grid"><div className="ops-stat-card"><span className="ops-stat-icon">{health?.ok?<CheckCircle2 size={18}/>:<Activity size={18}/>}</span><span>API health</span><strong>{health?.ok?"Online":"—"}</strong><small>{health?.database||"Waiting for check"}</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><Users size={18}/></span><span>Total accounts</span><strong>{accounts.length}</strong><small>Across platform roles</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><UserCheck size={18}/></span><span>Active</span><strong>{active}</strong><small>Enabled accounts</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><UserX size={18}/></span><span>Suspended</span><strong>{suspended}</strong><small>Access disabled</small></div></div><div className="ops-feature-grid"><div className="ops-feature-card"><span className="ops-kicker">Access posture</span><h4>Active access</h4><div className="ops-progress"><span style={{width:`${accounts.length?Math.round(active/accounts.length*100):0}%`}}/></div><p>{accounts.length?Math.round(active/accounts.length*100):0}% enabled</p></div><div className="ops-feature-card"><span className="ops-kicker">Role mix</span><h4>Staff distribution</h4><div className="ops-feature-list">{(summary?.role_counts||roles.map(r=>({role:r,count:accounts.filter(a=>a.role===r).length}))).slice(0,5).map(r=><div key={r.role}><span>{r.role}</span><strong>{r.count}</strong></div>)}</div></div><div className="ops-feature-card"><span className="ops-kicker">Recent signals</span><h4>Audit activity</h4><div className="ops-detail-grid"><div className="ops-detail-item"><span>Events loaded</span><strong>{audit.length}</strong></div><div className="ops-detail-item"><span>Service</span><strong>{health?.service||"—"}</strong></div></div></div></div></section>
 <section id="system-health" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">System health</span><h3>Service status</h3><p>Run the existing health check and see basic runtime signals.</p></div><button className="ops-button ops-button--tonal ops-button--small" onClick={refresh}><RefreshCw size={14}/> Check now</button></div><div className="ops-health-grid"><div className="ops-health-card"><span>Status</span><strong>{health?.ok?"Healthy":"Unavailable"}</strong></div><div className="ops-health-card"><span>Service</span><strong>{health?.service||"—"}</strong></div><div className="ops-health-card"><span>Database</span><strong>{health?.database||"—"}</strong></div></div></section>
 <section id="account-management" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Account management</span><h3>Staff access</h3><p>Filter by role, search accounts, and suspend or reactivate access.</p></div><span className="ops-inline-count">{filtered.length}</span></div><div className="ops-toolbar"><label className="ops-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts…"/></label><select className="ops-select" value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> CSV</button></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Account</th><th>Role</th><th>Department</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="ops-table-empty">Loading accounts…</td></tr>:filtered.length===0?<tr><td colSpan={5} className="ops-table-empty"><Users size={18}/> No matching accounts.</td></tr>:filtered.map(a=><tr key={a.id}><td><strong>{a.full_name||a.email}</strong><span>{a.email}</span></td><td>{a.role}</td><td>{a.department||"—"}</td><td><span className={`ops-status-badge ${a.active?"is-success":"is-danger"}`}>{a.active?"Active":"Suspended"}</span></td><td><button className={`ops-button ops-button--small ${a.active?"ops-button--danger":"ops-button--tonal"}`} disabled={savingId===a.id} onClick={()=>toggle(a)}>{savingId===a.id?"Saving…":a.active?"Suspend":"Activate"}</button></td></tr>)}</tbody></table></div></section>
 <section id="audit-log" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Audit log</span><h3>Recent activity</h3><p>Most recent recorded actions, newest first.</p></div><span className="ops-inline-count">{audit.length}</span></div><div className="ops-feature-list">{audit.slice(0,15).map((row,i)=><div key={row.id||i}><span>{row.action||"Audit event"} · {row.note||""}</span><strong>{row.created_at?new Date(row.created_at).toLocaleString():"—"}</strong></div>)}</div></section>
 </RoleDashboardShell>
}
