import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AlertCircle, Ban, CalendarDays, CheckCircle2, Clock3, Download, FileCheck2, RefreshCw, Search, X, Eye, Printer } from "lucide-react";
import { RoleDashboardShell } from "@/components/dashboard/RoleDashboardShell";
import { apiGetAllDarshanRequests, apiUpdateDarshanStatus, apiGetMandirSummary } from "@/lib/api";
import "./operations.css";

const navItems=[
 {id:"overview",label:"Overview",href:"#overview",description:"Darshan activity, queue health, and today’s workload."},
 {id:"pass-requests",label:"Pass requests",href:"#pass-requests",description:"Review, issue, decline, inspect, and print Darshan requests."},
 {id:"schedule",label:"Darshan schedule",href:"#schedule",description:"See requested dates and workload grouped by day."},
];
export const Route=createFileRoute("/dashboard/mandir")({head:()=>({meta:[{title:"Mandir Committee Dashboard — PRANASAKHA"}]}),component:MandirDashboard});

function MandirDashboard(){
 const [requests,setRequests]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[savingId,setSavingId]=useState(null),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[date,setDate]=useState(""),[selected,setSelected]=useState(null);
 async function refresh(){setError("");try{const [items,s]=await Promise.all([apiGetAllDarshanRequests(),apiGetMandirSummary()]);setRequests(items||[]);setSummary(s||null)}catch(e){setError(e.message||"Could not load Darshan operations.")}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{refresh()},[]);
 async function update(item,nextStatus){setSavingId(item.id);setError("");try{await apiUpdateDarshanStatus(item.id,nextStatus);setSelected(null);await refresh()}catch(e){setError(e.message||"Could not update the request.")}finally{setSavingId(null)}}
 const filtered=useMemo(()=>requests.filter(i=>{const hay=`${i.full_name||""} ${i.email||""} ${i.purpose||""}`.toLowerCase();const q=hay.includes(query.trim().toLowerCase());const s=status==="all"||i.status===status;const d=!date||String(i.requested_date||"").slice(0,10)===date;return q&&s&&d}),[requests,query,status,date]);
 const counts={pending:requests.filter(x=>x.status==="pending").length,issued:requests.filter(x=>x.status==="issued").length,declined:requests.filter(x=>x.status==="declined").length,today:summary?.today_count??requests.filter(x=>String(x.created_at||"").slice(0,10)===new Date().toISOString().slice(0,10)).length};
 const grouped=useMemo(()=>{const m={};requests.forEach(r=>{const key=r.requested_date||"No date";(m[key]??=[]).push(r)});return Object.entries(m).sort(([a],[b])=>a.localeCompare(b))},[requests]);
 function exportCsv(){const rows=[["Doctor","Email","Purpose","Requested date","Status"],...filtered.map(r=>[r.full_name||"",r.email||"",r.purpose||"",r.requested_date||"",r.status||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="darshan-requests.csv";a.click();URL.revokeObjectURL(a.href)}
 return <RoleDashboardShell role="Mandir Committee" title="Darshan operations" description="Coordinate Darshan requests with compact, auditable actions." navItems={navItems} searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search doctor or purpose…">
 {error?<div className="ops-alert ops-alert--error"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss"><X size={15}/></button></div>:null}
 <section id="overview" className="dashboard-view ops-overview"><div className="ops-hero"><div><span className="ops-kicker">Mandir workspace</span><h2>Darshan control center</h2><p>Turn incoming requests into clear decisions while keeping the daily queue predictable.</p></div><button className="ops-button ops-button--tonal" onClick={()=>{setRefreshing(true);refresh()}} disabled={refreshing}><RefreshCw size={16} className={refreshing?"ops-spin":""}/> Refresh</button></div>
 <div className="ops-stat-grid"><div className="ops-stat-card"><span className="ops-stat-icon"><Clock3 size={18}/></span><span>Pending</span><strong>{counts.pending}</strong><small>Awaiting committee action</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><CheckCircle2 size={18}/></span><span>Issued</span><strong>{counts.issued}</strong><small>Active passes</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><Ban size={18}/></span><span>Declined</span><strong>{counts.declined}</strong><small>Closed as declined</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><CalendarDays size={18}/></span><span>Today</span><strong>{counts.today}</strong><small>Requests created today</small></div></div>
 <div className="ops-feature-grid"><div className="ops-feature-card"><span className="ops-kicker">Queue health</span><h4>Decision mix</h4><div className="ops-feature-list"><div><span>Pending</span><strong>{counts.pending}</strong></div><div><span>Issued</span><strong>{counts.issued}</strong></div><div><span>Declined</span><strong>{counts.declined}</strong></div></div></div><div className="ops-feature-card"><span className="ops-kicker">Coverage</span><h4>Issued share</h4><p>Percentage of all requests that have been issued.</p><div className="ops-progress"><span style={{width:`${requests.length?Math.round(counts.issued/requests.length*100):0}%`}}/></div><p>{requests.length?Math.round(counts.issued/requests.length*100):0}% of {requests.length} requests</p></div><div className="ops-feature-card"><span className="ops-kicker">Actions</span><h4>Operator shortcuts</h4><div className="ops-chip-row"><button className="ops-button ops-button--tonal ops-button--small" onClick={()=>{setStatus("pending");location.hash="#pass-requests"}}>Pending only</button><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> Export CSV</button></div></div></div></section>
 <section id="pass-requests" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Darshan requests</span><h3>Incoming queue</h3><p>Inspect a request before issuing or declining it.</p></div><span className="ops-inline-count">{filtered.length}</span></div><div className="ops-toolbar"><label className="ops-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search doctor, email, purpose…"/></label><select className="ops-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="issued">Issued</option><option value="declined">Declined</option></select><input className="ops-select" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> CSV</button></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Doctor</th><th>Purpose</th><th>Requested</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="ops-table-empty">Loading requests…</td></tr>:filtered.length===0?<tr><td colSpan={5} className="ops-table-empty"><FileCheck2 size={18}/> No matching requests.</td></tr>:filtered.map(item=><tr key={item.id}><td><strong>{item.full_name||item.email}</strong><span>{item.email||"—"}</span></td><td>{item.purpose||"—"}</td><td>{item.requested_date||item.created_at?new Date(item.requested_date||item.created_at).toLocaleDateString():"—"}</td><td><span className={`ops-status-badge ${item.status==="issued"?"is-success":item.status==="declined"?"is-danger":"is-warning"}`}>{item.status||"pending"}</span></td><td><div className="ops-chip-row"><button className="ops-export-button" onClick={()=>setSelected(item)}><Eye size={14}/> View</button><button className="ops-button ops-button--primary ops-button--small" disabled={savingId===item.id||item.status==="issued"} onClick={()=>update(item,"issued")}>{item.status==="issued"?"Issued":savingId===item.id?"Saving…":"Issue"}</button>{item.status!=="declined"?<button className="ops-button ops-button--danger ops-button--small" disabled={savingId===item.id} onClick={()=>update(item,"declined")}>Decline</button>:null}</div></td></tr>)}</tbody></table></div></section>
 <section id="schedule" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Schedule</span><h3>Requested dates</h3><p>Workload grouped by the date requested by doctors.</p></div></div><div className="ops-feature-list">{grouped.slice(0,12).map(([d,items])=><div key={d}><span>{d}</span><strong>{items.length} request{items.length===1?"":"s"}</strong></div>)}{!grouped.length?<div><span>No scheduled requests</span><strong>0</strong></div>:null}</div></section>
 {selected?<div className="ops-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="ops-modal" role="dialog" aria-modal="true"><div className="ops-modal-header"><div><h3>Darshan request</h3><p>Review the complete request before taking action.</p></div><button className="ops-modal-close" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="ops-detail-grid" style={{marginTop:14}}><div className="ops-detail-item"><span>Doctor</span><strong>{selected.full_name||selected.email||"—"}</strong></div><div className="ops-detail-item"><span>Email</span><strong>{selected.email||"—"}</strong></div><div className="ops-detail-item"><span>Purpose</span><strong>{selected.purpose||"—"}</strong></div><div className="ops-detail-item"><span>Requested date</span><strong>{selected.requested_date||"—"}</strong></div><div className="ops-detail-item"><span>Status</span><strong>{selected.status||"pending"}</strong></div></div><div className="ops-modal-footer"><button className="ops-export-button" onClick={()=>window.print()}><Printer size={14}/> Print</button><button className="ops-button ops-button--tonal" onClick={()=>setSelected(null)}>Close</button>{selected.status!=="declined"?<button className="ops-button ops-button--danger" onClick={()=>update(selected,"declined")}>Decline</button>:null}{selected.status!=="issued"?<button className="ops-button ops-button--primary" onClick={()=>update(selected,"issued")}>Issue pass</button>:null}</div></div></div>:null}
 </RoleDashboardShell>
}
