import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AlertCircle,CheckCircle2,Clock3,Download,Eye,FileText,PackageCheck,Plane,RefreshCw,Search,ShieldCheck,X } from "lucide-react";
import { RoleDashboardShell } from "@/components/dashboard/RoleDashboardShell";
import { apiGetTravelQueue,apiGenerateVisaLetter,apiUpdateTravelPickupStatus,apiGetTravelSummary } from "@/lib/api";
import "./operations.css";
const navItems=[{id:"overview",label:"Overview",href:"#overview",description:"Travel readiness, support-letter workload, and handoff status."},{id:"visa-queue",label:"Visa support queue",href:"#visa-queue",description:"Generate letters and progress arrival handoffs."},{id:"readiness",label:"Readiness board",href:"#readiness",description:"Find doctors with missing travel information before arrival."}];
export const Route=createFileRoute("/dashboard/travel")({head:()=>({meta:[{title:"Travel & Visa Desk Dashboard — PRANASAKHA"}]}),component:TravelDashboard});
function TravelDashboard(){
 const [entries,setEntries]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[pickup,setPickup]=useState("all"),[savingId,setSavingId]=useState(null),[selected,setSelected]=useState(null);
 async function refresh(){setError("");try{const [rows,s]=await Promise.all([apiGetTravelQueue(),apiGetTravelSummary()]);setEntries(rows||[]);setSummary(s||null)}catch(e){setError(e.message||"Could not load Travel operations.")}finally{setLoading(false);setRefreshing(false)}}useEffect(()=>{refresh()},[]);
 async function letter(e){setSavingId(e.user_id);try{await apiGenerateVisaLetter(e.user_id);await refresh()}catch(x){setError(x.message||"Could not generate the letter.")}finally{setSavingId(null)}}
 async function pickupUpdate(e,next){setSavingId(e.user_id);try{await apiUpdateTravelPickupStatus(e.user_id,next);await refresh()}catch(x){setError(x.message||"Could not update pickup status.")}finally{setSavingId(null)}}
 const filtered=useMemo(()=>entries.filter(e=>{const hay=`${e.full_name||""} ${e.email||""} ${e.specialty||""} ${e.preferred_institutions||""} ${e.airport||""} ${e.flight_details||""}`.toLowerCase();return hay.includes(query.trim().toLowerCase())&&(status==="all"||e.letter_status===status)&&(pickup==="all"||e.pickup_status===pickup)}),[entries,query,status,pickup]);
 const generated=entries.filter(x=>x.letter_status==="generated").length,pending=entries.length-generated,ready=entries.filter(x=>x.pickup_status==="ready").length,collected=entries.filter(x=>x.pickup_status==="collected").length;
 function exportCsv(){const rows=[["Doctor","Email","Specialty","Institution","Airport","Flight","Letter","Pickup"],...filtered.map(e=>[e.full_name||"",e.email||"",e.specialty||"",e.preferred_institutions||"",e.airport||"",e.flight_details||"",e.letter_status||"",e.pickup_status||""])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="travel-readiness.csv";a.click();URL.revokeObjectURL(a.href)}
 return <RoleDashboardShell role="Travel & Visa Desk" title="Travel coordination" description="Prepare visa support and keep every arrival handoff visible." navItems={navItems} searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search doctor, specialty or flight…">
 {error?<div className="ops-alert ops-alert--error"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError("")} aria-label="Dismiss"><X size={15}/></button></div>:null}
 <section id="overview" className="dashboard-view ops-overview"><div className="ops-hero"><div><span className="ops-kicker">Travel workspace</span><h2>Visa & arrival control center</h2><p>Move approved doctors from documentation to letter generation and arrival handoff.</p></div><button className="ops-button ops-button--tonal" onClick={()=>{setRefreshing(true);refresh()}} disabled={refreshing}><RefreshCw size={16} className={refreshing?"ops-spin":""}/> Refresh</button></div><div className="ops-stat-grid"><div className="ops-stat-card"><span className="ops-stat-icon"><Clock3 size={18}/></span><span>Letter pending</span><strong>{pending}</strong><small>Needs generation</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><FileText size={18}/></span><span>Generated</span><strong>{generated}</strong><small>Support letters ready</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><PackageCheck size={18}/></span><span>Pickup ready</span><strong>{ready}</strong><small>Awaiting arrival</small></div><div className="ops-stat-card"><span className="ops-stat-icon"><CheckCircle2 size={18}/></span><span>Collected</span><strong>{collected}</strong><small>Handoffs completed</small></div></div><div className="ops-feature-grid"><div className="ops-feature-card"><span className="ops-kicker">Readiness</span><h4>Letter completion</h4><p>Share of the queue with generated support letters.</p><div className="ops-progress"><span style={{width:`${entries.length?Math.round(generated/entries.length*100):0}%`}}/></div><p>{entries.length?Math.round(generated/entries.length*100):0}% complete</p></div><div className="ops-feature-card"><span className="ops-kicker">Handoffs</span><h4>Pickup completion</h4><p>Share of travel records already collected.</p><div className="ops-progress"><span style={{width:`${entries.length?Math.round(collected/entries.length*100):0}%`}}/></div><p>{entries.length?Math.round(collected/entries.length*100):0}% collected</p></div><div className="ops-feature-card"><span className="ops-kicker">Actions</span><h4>Desk shortcuts</h4><div className="ops-chip-row"><button className="ops-button ops-button--tonal ops-button--small" onClick={()=>{setStatus("not_generated");location.hash="#visa-queue"}}>Pending letters</button><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> Export CSV</button></div></div></div></section>
 <section id="visa-queue" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Visa & travel</span><h3>Approved doctor queue</h3><p>Generate letters, inspect travel details, and progress pickup status.</p></div><span className="ops-inline-count">{filtered.length}</span></div><div className="ops-toolbar"><label className="ops-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search doctor, institution, airport…"/></label><select className="ops-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All letters</option><option value="not_generated">Not generated</option><option value="generated">Generated</option></select><select className="ops-select" value={pickup} onChange={e=>setPickup(e.target.value)}><option value="all">All pickups</option><option value="pending">Pending</option><option value="ready">Ready</option><option value="collected">Collected</option></select><button className="ops-export-button" onClick={exportCsv}><Download size={14}/> CSV</button></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Doctor</th><th>Specialty</th><th>Institution</th><th>Letter</th><th>Pickup</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="ops-table-empty">Loading travel queue…</td></tr>:filtered.length===0?<tr><td colSpan={6} className="ops-table-empty"><Plane size={18}/> No matching doctors.</td></tr>:filtered.map(e=><tr key={e.user_id}><td><strong>{e.full_name||e.email}</strong><span>{e.email||"—"}</span></td><td>{e.specialty||"—"}</td><td>{e.preferred_institutions||"—"}</td><td><span className={`ops-status-badge ${e.letter_status==="generated"?"is-success":"is-warning"}`}>{e.letter_status==="generated"?"Generated":"Pending"}</span></td><td><span className={`ops-status-badge ${e.pickup_status==="collected"?"is-success":e.pickup_status==="ready"?"is-info":"is-warning"}`}>{e.pickup_status||"pending"}</span></td><td><div className="ops-chip-row"><button className="ops-export-button" onClick={()=>setSelected(e)}><Eye size={14}/> View</button><button className="ops-button ops-button--primary ops-button--small" disabled={savingId===e.user_id||e.letter_status==="generated"} onClick={()=>letter(e)}>{savingId===e.user_id?"Saving…":e.letter_status==="generated"?"Generated":"Generate letter"}</button><button className="ops-button ops-button--tonal ops-button--small" disabled={savingId===e.user_id||e.pickup_status==="collected"} onClick={()=>pickupUpdate(e,e.pickup_status==="pending"?"ready":"collected")}>{e.pickup_status==="pending"?"Mark ready":e.pickup_status==="ready"?"Mark collected":"Collected"}</button></div></td></tr>)}</tbody></table></div></section>
 <section id="readiness" className="dashboard-view ops-card"><div className="ops-card-header"><div><span className="ops-kicker">Readiness board</span><h3>Travel information signals</h3><p>Use available profile and travel fields to find records that need operator attention.</p></div></div><div className="ops-feature-list">{entries.filter(e=>!e.airport||!e.flight_details).slice(0,15).map(e=><div key={e.user_id}><span>{e.full_name||e.email} · {!e.airport?"Airport missing":"Flight details missing"}</span><strong>{e.pickup_status||"pending"}</strong></div>)}{entries.every(e=>e.airport&&e.flight_details)&&<div><span><ShieldCheck size={14}/> All loaded records have airport + flight details</span><strong>Ready</strong></div>}</div></section>
 {selected?<div className="ops-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="ops-modal"><div className="ops-modal-header"><div><h3>Travel record</h3><p>Review the available arrival information.</p></div><button className="ops-modal-close" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="ops-detail-grid" style={{marginTop:14}}><div className="ops-detail-item"><span>Doctor</span><strong>{selected.full_name||selected.email}</strong></div><div className="ops-detail-item"><span>Email</span><strong>{selected.email||"—"}</strong></div><div className="ops-detail-item"><span>Airport</span><strong>{selected.airport||"Not provided"}</strong></div><div className="ops-detail-item"><span>Flight</span><strong>{selected.flight_details||"Not provided"}</strong></div><div className="ops-detail-item"><span>Letter</span><strong>{selected.letter_status||"not_generated"}</strong></div><div className="ops-detail-item"><span>Pickup</span><strong>{selected.pickup_status||"pending"}</strong></div></div><div className="ops-modal-footer"><button className="ops-button ops-button--tonal" onClick={()=>setSelected(null)}>Close</button></div></div></div>:null}
 </RoleDashboardShell>
}
