ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider TEXT NOT NULL DEFAULT 'password';
ALTER TABLE users ADD COLUMN IF NOT EXISTS provider_subject TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS service_category TEXT NOT NULL DEFAULT 'doctors';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS norms_accepted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS consent_data BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS consent_declaration BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS consent_seva BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_provider_subject ON users(auth_provider, provider_subject) WHERE provider_subject IS NOT NULL;

