/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as VerifyTokenRouteImport } from "./routes/verify.$token";
import { Route as DashboardLayoutRouteImport } from "./routes/dashboard/_layout";
import { Route as DashboardAccommodationRouteImport } from "./routes/dashboard/accommodation";
import { Route as DashboardAdminRouteImport } from "./routes/dashboard/admin";
import { Route as DashboardDirectorateRouteImport } from "./routes/dashboard/directorate";
import { Route as DashboardDoctorRouteImport } from "./routes/dashboard/doctor";
import { Route as DashboardHodRouteImport } from "./routes/dashboard/hod";
import { Route as DashboardItRouteImport } from "./routes/dashboard/it";
import { Route as DashboardMandirRouteImport } from "./routes/dashboard/mandir";
import { Route as DashboardTravelRouteImport } from "./routes/dashboard/travel";
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
});
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: "/verify/$token",
  path: "/verify/$token",
  getParentRoute: () => rootRouteImport,
});
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: "/dashboard/_layout",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const DashboardAccommodationRoute = DashboardAccommodationRouteImport.update({
  id: "/dashboard/accommodation",
  path: "/dashboard/accommodation",
  getParentRoute: () => rootRouteImport,
});
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: "/dashboard/admin",
  path: "/dashboard/admin",
  getParentRoute: () => rootRouteImport,
});
const DashboardDirectorateRoute = DashboardDirectorateRouteImport.update({
  id: "/dashboard/directorate",
  path: "/dashboard/directorate",
  getParentRoute: () => rootRouteImport,
});
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: "/dashboard/doctor",
  path: "/dashboard/doctor",
  getParentRoute: () => rootRouteImport,
});
const DashboardHodRoute = DashboardHodRouteImport.update({
  id: "/dashboard/hod",
  path: "/dashboard/hod",
  getParentRoute: () => rootRouteImport,
});
const DashboardItRoute = DashboardItRouteImport.update({
  id: "/dashboard/it",
  path: "/dashboard/it",
  getParentRoute: () => rootRouteImport,
});
const DashboardMandirRoute = DashboardMandirRouteImport.update({
  id: "/dashboard/mandir",
  path: "/dashboard/mandir",
  getParentRoute: () => rootRouteImport,
});
const DashboardTravelRoute = DashboardTravelRouteImport.update({
  id: "/dashboard/travel",
  path: "/dashboard/travel",
  getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ProfileRoute: ProfileRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardAccommodationRoute: DashboardAccommodationRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDirectorateRoute: DashboardDirectorateRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardHodRoute: DashboardHodRoute,
  DashboardItRoute: DashboardItRoute,
  DashboardMandirRoute: DashboardMandirRoute,
  DashboardTravelRoute: DashboardTravelRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
